<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'CmsImageMap\Mapping\AreaInterface'             => __DIR__ . '/src/Mapping/AreaInterface.php',
    'CmsImageMap\Mapping\ImageMappableInterface'    => __DIR__ . '/src/Mapping/ImageMappableInterface.php',
    'CmsImageMap\Mapping\MapInterface'              => __DIR__ . '/src/Mapping/MapInterface.php',
    'CmsImageMap\Mapping\Traits\ImageMappableTrait' => __DIR__ . '/src/Mapping/Traits/ImageMappableTrait.php',
    'CmsImageMap\Module'                            => __DIR__ . '/src/Module.php',
    'CmsImageMap\Controller\AdminController'        => __DIR__ . '/src/Mvc/Controller/AdminController.php',
    'CmsImageMap\View\Helper\ImageMap'              => __DIR__ . '/src/View/Helper/ImageMap.php',
    'CmsImageMapTest\Framework\TestCase'            => __DIR__ . '/tests/Framework/TestCase.php',
    'CmsImageMapTest\SampleTest'                    => __DIR__ . '/tests/SampleTest.php',
);
